/**
 * El tempo (BPM) de los temas de la playlist, por título (como en content/musica.ts →
 * `fichas`): Yo Da asiente a ese ritmo mientras suena (components/YoSoy.tsx). Los pasó
 * Lucas (de SongBPM, GetSongBPM y SongData; algunos, aproximados). Los que faltan van a
 * un ritmo medio (BPM_POR_DEFECTO) hasta que se sumen.
 */
export const BPM_POR_DEFECTO = 110;

export const bpm: Record<string, number> = {
  "Buk-In-Hamm Palace": 103,
  "Velha Infância": 113,
  "Precious": 105,
  "Génesis": 143,
  "The Heat Is On": 150,
  "The Way It Is": 111,
  "Turn Around": 120,
  "Johnny Come Home": 133,
  "7 Seconds (feat. Neneh Cherry)": 154,
  "Shot in the Back of the Head": 98,
  "Deeper and Deeper": 120,
  "Something About You": 105,
  "A Trick of the Light": 150,
  "Tudo Vai Dar Certo": 72,
  "Money For Nothing": 134,
  "Other Side Of The World": 80,
  "5 23": 110,
  "Elysium": 80,
  "Angelic Voices": 120,
  "The Oh Of Pleasure / Ray Lynch": 97,
  "Enjoy the Silence": 113,
  "Sweet Disposition": 129,
  "Eyes on Fire": 145,
  "Bamboléo": 120,
  "Bonito": 114,
  "I Like It Like That": 133,
  "You Make Me Feel (Mighty Real)": 135,
  "Dreamers": 103,
  "Wuthering Heights": 124,
  "Pale Shelter": 119,
  "Eminence Front": 98,
  "While My Guitar Gently Weeps": 135,
  "Talking In Your Sleep": 125,
  "Lucky Man": 76,
  "Dream On": 80,
  "Pleasure": 103,
  "Your Song": 133,
  "Beautiful": 76,
  "Sowing The Seeds Of Love": 86.5,
  "Solsbury Hill": 103,
  "I Am That I Am": 146,
  "Rezo por Vos": 121,
  "Gravity Of Love": 140,
  "Modern Crusaders": 115,
  "Everything Counts": 114,
  "I Ran (So Far Away)": 145,
  "Mammagamma": 130,
  "Brown Bag": 143,
  "Point of View": 129,
  "Estallando Desde el Océano": 167,
  "The Look": 85,
  "Safe and Sound": 115,
  "Got To Keep On": 125,
  "Cuidado, Peligro, Eclipse": 118,
  "Fascination": 128,
  "Free tibet": 140,
  "Piece of Pie": 151,
  "Vuelta por el Universo": 107,
  "Stubborn Love": 115,
  "Dark Necessities": 91,
  "Macho": 110,
  "Puppet Theatre": 120,
  "Make It Wit Chu": 92,
  "Riptide": 102,
  "Fallin'": 96,
  "Black Horse And The Cherry Tree": 104,
  "King Rat": 123,
  "Nothing In My Way": 113,
  "Connected": 119,
  "Diamonds Never Die": 100,
  "Give Up The Funk (Tear The Roof Off The Sucker)": 113,
  "Viviendo": 97,
  "Ordinary Man": 90,
  "Notorious": 113,
  "Shankara": 138,
  "Cold Little Heart": 110,
  "Forget Me Nots": 114,
  "This Is the Day": 142,
  "Arrival": 80,
  "Судно (Борис Рыжий)": 117,
  "На Дне": 110,
  "Glue": 130,
  "Some Velvet Morning (feat. Kate Moss)": 123,
  "Bete Balanço": 126,
  "Não Adianta": 145,
  "Calling America": 127,
  "Wait a Minute!": 101,
  "Meet Me Halfway": 130,
  "Blue Monday '88": 130,
  "Advice For The Young At Heart": 105,
  "Somebody's Watching Me": 124,
  "Bigmouth Strikes Again": 164,
  "Walk The Night": 125,
  "A Real Hero": 100,
  "El Día Que Apagaron La Luz": 90,
  "Black Velvet": 91,
  "A Little Respect": 114,
  "Break It Down Again": 96,
  "Vivo": 90,
  "Poison Lips": 126,
};

/** Cada cuánto asiente (en segundos): una vez por tiempo en los temas lentos, una cada dos en los rápidos. */
export function periodoAsentir(titulo: string | null | undefined): number {
  const b = (titulo && bpm[titulo]) || BPM_POR_DEFECTO;
  return (60 / b) * (b >= 100 ? 2 : 1);
}
