/**
 * MÚSICA DE FONDO: temas de la playlist de Julián en Spotify, «The Way It Is»
 * (https://open.spotify.com/playlist/6kKcFrfXA72AnV8tfMIRUE). Suenan al azar con el
 * reproductor oficial de Spotify, solo si la persona toca play.
 * Para actualizar la lista: python3 herramientas/musica_playlist.py
 */
export const playlist = "6kKcFrfXA72AnV8tfMIRUE";

export const temas: string[] = [
  "1EaoyUXLaWFFA1bbE1KMI4", "1mSxbLW7fKABfeY4lGpg0E", "1cBxAm8a0fENn2ix3Dfm3u", "1yEBMvOYbhJJTX7x3iW41O",
  "0PXw9NKvolWTo7U9JkNzmc", "6V50MyHPGhEmwYu0Wdyf0t", "17m6ziTxbgxdTT3oxfUY9Q", "4fFxkU9C7prSviiYtvlV8V",
  "4sv1iemiMkkZVTUbV16C8L", "48K4U97b0swlpB01Ead78F", "6KU8g98m1tcrUXRNjPQeOI", "4fE3Pyz3Jfu7LL5NUB1iMl",
  "1rCPg5GOtes0FIo1BzgvUi", "6B8pYtoS3XHrc821hExWf6", "4nFNJmjfgBF7jwv2oBC45b", "4A9E08l34BkPsCDAmOpHxb",
  "7rGEbcLvRsoehrdQ2LC50G", "1b2i3kaTfItjvYBVA3Tpie", "4ig6F41uvpGxtFBmWVRPzj", "3wNdebqmHRSVm17wWKu8Kw",
  "6WK9dVrRABMkUXFLNlgWFh", "49x8Zp5wDjoquBE1THLLCV", "3XHrTm6WE2BOHafLwTT3GR", "3iB8eciGU9vZkaDYkz7Ir9",
  "5FiB1uNoGZE4PenzZd7Imu", "6Wy3X4jSszfisnRscJCHdq", "3lwNHGO5yJLNpHsMlvL9IF", "6yOIdK2nKErlhyo5u7y81B",
  "5YSI1311X8t31PBjkBG4CZ", "0Xam0zVac3hKWWN4OQ5Gdr", "6HhVHZTzhjvS5erfCm4roh", "1T94tcUfe2X74nriMCAWQa",
  "7fRvtXvJMpGfTLdF0M09a1", "2mxPSHEwjJWOQS7lGw6btF", "5MxNLUsfh7uzROypsoO5qe", "19ts4uqOimLvSbu4DyOWE2",
  "1UmIWsuzcitp1VhsEKviJZ", "3TCauNPqFiniaYHBvEVoHG", "0PbAyLrJRDxckQBLQ2Addc", "6vZZtivPrtpggT5SSXsYTy",
  "2PyDqCtFcXsucZqTF4rE3i", "6dOzqs6o4DNzXs4jF2v1Yq", "3RSMFb9dHXNWZw8YwYGepI", "65fqcmj2M1EiERwDoIflDt",
  "4oWQeGyPFyr4EpTrv5v0gJ", "4OdhffpvG3HxDJMxYOKh97", "2H2riBoltlfKrU7i495hvf", "1hk1xqRPp6qX9CpiDeI4Bs",
  "1Jlt67b4oOhCoFW9GQwL9T", "7379uubtjZDDT6Phsj4nhj", "6zfczP87XO2SxWlQtnjFNa", "5pqbHlHaVbkHJQlsAxhcZM",
  "4vh6Rn6FVG4w79JmlZ5p7d", "2niXWS7JOhbUm5oI2awwYE", "6tcdlfcRP08NFleBmSArlZ", "1form6XxaJCcp9CoU3Qxos",
  "1GXHrTSeLX8RX4EClAt4OO", "7uY3xheR58xt98wb8BIz21", "7x46YkKAwp3yZpaa72n5Mu", "2oaK4JLVnmRGIO9ytBE1bt",
  "0NVNmybggOg7HqjcxCkvpq", "3pFlX8RJORG2EX3v6GK8ya", "6GyDY0yE47rfk8pcuKhioh", "7yq4Qj7cqayVTp3FF9CWbm",
  "3unsLiH5FXmaDWtT5Imolu", "0qAMjeQFyd1qD0LDiV8gWp", "6Z3pIqEp5n5faSopwto0tB", "7falOwHJ9MjskdcNehIh79",
  "1ZoE2naC9ySlPLdBZhS1rM", "7bLDM3CuuoWI8rxnVwG635", "4XRkQloZFcRrCONN7ZQ49Y", "3WBe1knGYKrtHMszE3UiWU",
  "5NbasL13ZyTu02X1R5XILi", "4yopZ4FVYS0RWKkCagdIEm", "3ChrN5yqI2YE6eAMMfvDs1", "7KX65PC1UZuImsUInThbav",
  "0jyfSxaTWKtBk3UepmyXqK", "5O7RVmqK3AYoFfyeafxOqH", "6tZ1vCG5l0656V1ZX8wZmC", "1SHB1hp6267UK9bJQUxYvO",
  "2aJDlirz6v2a4HREki98cP", "3rClbCwDdkt8UbEEPZBHGF", "72OI2uQwj4pHetYlCplkSi", "0SrDqCmn2ClzEzNkAZYc2Y",
  "7rud54XCjLv3AQbaUAtxU1", "72eXfQYeBW1KsZEZ4fMnxP", "0y60itmpH0aPKsFiGxmtnh", "3F9ByoUqu31xU0I3G5xfVg",
  "31MOjWj3CT3dCQsMV2b8Wu", "3BjD16l0CBQxUvcRI7vLWN", "2gGdO0zLa9W8ce1Ig0BzFK", "2OErSh4oVVAUll0vHxdr6p",
  "7C9G9grdrb4fWcRReE1ImC", "1aJrVsHwcQMZ8TZ6mlvT5J", "2ls5Nls2vswpcxsC0HlVZr", "1KU5EHSz04JhGg3rReGJ0N",
  "1QRvbZIBvpQmoCyGNyaIwq", "15kc3DJyYixeEEq5kRRrOm", "3AVSuWS3i6KpNza7rIvzD3", "2BIC788t4sLhFM8MpZIclI",
];

/** Título y artista de cada tema (para que Yo Da comente lo que suena). */
export const fichas: Record<string, [titulo: string, artista: string]> = {
  "1EaoyUXLaWFFA1bbE1KMI4": ["Buk-In-Hamm Palace", "Peter Tosh"],
  "1mSxbLW7fKABfeY4lGpg0E": ["Velha Infância", "Tribalistas"],
  "1cBxAm8a0fENn2ix3Dfm3u": ["Precious", "Depeche Mode"],
  "1yEBMvOYbhJJTX7x3iW41O": ["Génesis", "Soda Stereo"],
  "0PXw9NKvolWTo7U9JkNzmc": ["The Heat Is On", "Glenn Frey"],
  "6V50MyHPGhEmwYu0Wdyf0t": ["The Way It Is", "Bruce Hornsby and the Range"],
  "17m6ziTxbgxdTT3oxfUY9Q": ["Turn Around", "Enigma"],
  "4fFxkU9C7prSviiYtvlV8V": ["Johnny Come Home", "Fine Young Cannibals"],
  "4sv1iemiMkkZVTUbV16C8L": ["7 Seconds (feat. Neneh Cherry)", "Youssou N'Dour, Neneh Cherry"],
  "48K4U97b0swlpB01Ead78F": ["Shot in the Back of the Head", "Moby"],
  "6KU8g98m1tcrUXRNjPQeOI": ["Deeper and Deeper", "Madonna"],
  "4fE3Pyz3Jfu7LL5NUB1iMl": ["Something About You", "Level 42"],
  "1rCPg5GOtes0FIo1BzgvUi": ["A Trick of the Light", "Villagers"],
  "6B8pYtoS3XHrc821hExWf6": ["Tudo Vai Dar Certo", "Natiruts, Amani Kush"],
  "4nFNJmjfgBF7jwv2oBC45b": ["Money For Nothing", "Dire Straits"],
  "4A9E08l34BkPsCDAmOpHxb": ["Other Side Of The World", "KT Tunstall"],
  "7rGEbcLvRsoehrdQ2LC50G": ["5 23", "Global Communication"],
  "1b2i3kaTfItjvYBVA3Tpie": ["Elysium", "Lisa Gerrard"],
  "4ig6F41uvpGxtFBmWVRPzj": ["Angelic Voices", "B-Tribe"],
  "3wNdebqmHRSVm17wWKu8Kw": ["The Oh Of Pleasure / Ray Lynch", "Ray Lynch, TOM CANNING"],
  "6WK9dVrRABMkUXFLNlgWFh": ["Enjoy the Silence", "Depeche Mode"],
  "49x8Zp5wDjoquBE1THLLCV": ["Sweet Disposition", "The Temper Trap"],
  "3XHrTm6WE2BOHafLwTT3GR": ["Eyes on Fire", "Blue Foundation"],
  "3iB8eciGU9vZkaDYkz7Ir9": ["Bamboléo", "Gipsy Kings"],
  "5FiB1uNoGZE4PenzZd7Imu": ["Bonito", "Jarabe De Palo"],
  "6Wy3X4jSszfisnRscJCHdq": ["I Like It Like That", "Pete Rodriguez"],
  "3lwNHGO5yJLNpHsMlvL9IF": ["You Make Me Feel (Mighty Real)", "Jimmy Somerville"],
  "6yOIdK2nKErlhyo5u7y81B": ["Dreamers", "Savoir Adore"],
  "5YSI1311X8t31PBjkBG4CZ": ["Wuthering Heights", "Kate Bush"],
  "0Xam0zVac3hKWWN4OQ5Gdr": ["Pale Shelter", "Tears For Fears"],
  "6HhVHZTzhjvS5erfCm4roh": ["Eminence Front", "The Who"],
  "1T94tcUfe2X74nriMCAWQa": ["While My Guitar Gently Weeps", "The Jeff Healey Band"],
  "7fRvtXvJMpGfTLdF0M09a1": ["Talking In Your Sleep", "The Romantics"],
  "2mxPSHEwjJWOQS7lGw6btF": ["Lucky Man", "The Verve"],
  "5MxNLUsfh7uzROypsoO5qe": ["Dream On", "Aerosmith"],
  "19ts4uqOimLvSbu4DyOWE2": ["Pleasure", "Justice"],
  "1UmIWsuzcitp1VhsEKviJZ": ["Your Song", "Ewan McGregor, Alessandro Safina"],
  "3TCauNPqFiniaYHBvEVoHG": ["Beautiful", "Christina Aguilera"],
  "0PbAyLrJRDxckQBLQ2Addc": ["Sowing The Seeds Of Love", "Tears For Fears"],
  "6vZZtivPrtpggT5SSXsYTy": ["Solsbury Hill", "Peter Gabriel"],
  "2PyDqCtFcXsucZqTF4rE3i": ["I Am That I Am", "Peter Tosh"],
  "6dOzqs6o4DNzXs4jF2v1Yq": ["Rezo por Vos", "Charly García"],
  "3RSMFb9dHXNWZw8YwYGepI": ["Gravity Of Love", "Enigma"],
  "65fqcmj2M1EiERwDoIflDt": ["Modern Crusaders", "Enigma"],
  "4oWQeGyPFyr4EpTrv5v0gJ": ["Everything Counts", "Depeche Mode"],
  "4OdhffpvG3HxDJMxYOKh97": ["I Ran (So Far Away)", "A Flock Of Seagulls"],
  "2H2riBoltlfKrU7i495hvf": ["Mammagamma", "The Alan Parsons Project"],
  "1hk1xqRPp6qX9CpiDeI4Bs": ["Brown Bag", "Boogaloo Joe Jones"],
  "1Jlt67b4oOhCoFW9GQwL9T": ["Point of View", "DB Boulevard"],
  "7379uubtjZDDT6Phsj4nhj": ["Estallando Desde el Océano", "Sumo"],
  "6zfczP87XO2SxWlQtnjFNa": ["The Look", "Metronomy"],
  "5pqbHlHaVbkHJQlsAxhcZM": ["Safe and Sound", "Justice"],
  "4vh6Rn6FVG4w79JmlZ5p7d": ["Got To Keep On", "The Chemical Brothers"],
  "2niXWS7JOhbUm5oI2awwYE": ["Cuidado, Peligro, Eclipse", "Agar Agar"],
  "6tcdlfcRP08NFleBmSArlZ": ["Fascination", "CLUBB3RS"],
  "1form6XxaJCcp9CoU3Qxos": ["Free tibet", "Hilight Tribe"],
  "1GXHrTSeLX8RX4EClAt4OO": ["Piece of Pie", "Stone Temple Pilots"],
  "7uY3xheR58xt98wb8BIz21": ["Vuelta por el Universo", "Gustavo Cerati, Daniel Melero"],
  "7x46YkKAwp3yZpaa72n5Mu": ["Stubborn Love", "The Lumineers"],
  "2oaK4JLVnmRGIO9ytBE1bt": ["Dark Necessities", "Red Hot Chili Peppers"],
  "0NVNmybggOg7HqjcxCkvpq": ["Macho", "Jaakko Eino Kalevi"],
  "3pFlX8RJORG2EX3v6GK8ya": ["Puppet Theatre", "Claptone, Peter Bjorn and John"],
  "6GyDY0yE47rfk8pcuKhioh": ["Make It Wit Chu", "Queens of the Stone Age"],
  "7yq4Qj7cqayVTp3FF9CWbm": ["Riptide", "Vance Joy"],
  "3unsLiH5FXmaDWtT5Imolu": ["Fallin'", "Alicia Keys"],
  "0qAMjeQFyd1qD0LDiV8gWp": ["Black Horse And The Cherry Tree", "KT Tunstall"],
  "6Z3pIqEp5n5faSopwto0tB": ["King Rat", "Modest Mouse"],
  "7falOwHJ9MjskdcNehIh79": ["Nothing In My Way", "Keane"],
  "1ZoE2naC9ySlPLdBZhS1rM": ["Connected", "Stereo MC's"],
  "7bLDM3CuuoWI8rxnVwG635": ["Diamonds Never Die", "Moriarty"],
  "4XRkQloZFcRrCONN7ZQ49Y": ["Give Up The Funk (Tear The Roof Off The Sucker)", "Parliament"],
  "3WBe1knGYKrtHMszE3UiWU": ["Viviendo", "Nach"],
  "5NbasL13ZyTu02X1R5XILi": ["Ordinary Man", "Chinese Man"],
  "4yopZ4FVYS0RWKkCagdIEm": ["Notorious", "Duran Duran"],
  "3ChrN5yqI2YE6eAMMfvDs1": ["Shankara", "Hilight Tribe"],
  "7KX65PC1UZuImsUInThbav": ["Cold Little Heart", "Michael Kiwanuka"],
  "0jyfSxaTWKtBk3UepmyXqK": ["Forget Me Nots", "Patrice Rushen"],
  "5O7RVmqK3AYoFfyeafxOqH": ["This Is the Day", "The The"],
  "6tZ1vCG5l0656V1ZX8wZmC": ["Arrival", "Steve Roach"],
  "1SHB1hp6267UK9bJQUxYvO": ["Судно (Борис Рыжий)", "Molchat Doma"],
  "2aJDlirz6v2a4HREki98cP": ["Glue", "BICEP"],
  "3rClbCwDdkt8UbEEPZBHGF": ["Some Velvet Morning (feat. Kate Moss)", "Primal Scream, Kate Moss"],
  "72OI2uQwj4pHetYlCplkSi": ["На Дне", "Molchat Doma"],
  "0SrDqCmn2ClzEzNkAZYc2Y": ["Bete Balanço", "Barão Vermelho"],
  "7rud54XCjLv3AQbaUAtxU1": ["Não Adianta", "Trio Mocoto"],
  "72eXfQYeBW1KsZEZ4fMnxP": ["Calling America", "Electric Light Orchestra"],
  "0y60itmpH0aPKsFiGxmtnh": ["Wait a Minute!", "WILLOW"],
  "3F9ByoUqu31xU0I3G5xfVg": ["Meet Me Halfway", "Black Eyed Peas"],
  "31MOjWj3CT3dCQsMV2b8Wu": ["Blue Monday '88", "New Order"],
  "3BjD16l0CBQxUvcRI7vLWN": ["Advice For The Young At Heart", "Tears For Fears"],
  "2gGdO0zLa9W8ce1Ig0BzFK": ["Somebody's Watching Me", "Rockwell"],
  "2OErSh4oVVAUll0vHxdr6p": ["Bigmouth Strikes Again", "The Smiths"],
  "7C9G9grdrb4fWcRReE1ImC": ["Walk The Night", "Skatt Bros"],
  "1aJrVsHwcQMZ8TZ6mlvT5J": ["A Real Hero", "College, Electric Youth"],
  "2ls5Nls2vswpcxsC0HlVZr": ["El Día Que Apagaron La Luz", "Sui Generis"],
  "1KU5EHSz04JhGg3rReGJ0N": ["Black Velvet", "Alannah Myles"],
  "1QRvbZIBvpQmoCyGNyaIwq": ["A Little Respect", "Erasure"],
  "15kc3DJyYixeEEq5kRRrOm": ["Break It Down Again", "Tears For Fears"],
  "3AVSuWS3i6KpNza7rIvzD3": ["Vivo", "Gustavo Cerati"],
  "2BIC788t4sLhFM8MpZIclI": ["Poison Lips", "Vitalic"],
};
